# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: Go

on: [push, workflow_dispatch]

jobs:
  go:
    uses: 'Th3Shadowbroker/workflows/.github/workflows/go.yml@0.0.1'